export const users = [
  {
    id: 1,
    fullName: 'John Doe',
    email: 'john.doe@example.com',
    role: 'admin',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: null,
  },

  {
    id: 3,
    fullName: 'James Johnson',
    email: 'james.johnson@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 4,
    fullName: 'Emily Davis',
    email: 'emily.davis@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    fullName: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'inactive',
    avatar: null,
  },
  {
    id: 6,
    fullName: 'Olivia Taylor',
    email: 'olivia.taylor@example.com',
    role: 'admin',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 7,
    fullName: 'William Anderson',
    email: 'william.anderson@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 8,
    fullName: 'Sophia Martinez',
    email: 'sophia.martinez@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: null,
  },
  {
    id: 9,
    fullName: 'Alexander Clark',
    email: 'alexander.clark@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 10,
    fullName: 'Ava Rodriguez',
    email: 'ava.rodriguez@example.com',
    role: 'admin',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: null,
  },
  {
    id: 11,
    fullName: 'Daniel Thomas',
    email: 'daniel.thomas@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 12,
    fullName: 'Mia Lee',
    email: 'mia.lee@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 13,
    fullName: 'Matthew White',
    email: 'matthew.white@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 14,
    fullName: 'Isabella Martinez',
    email: 'isabella.martinez@example.com',
    role: 'admin',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: null,
  },
  {
    id: 15,
    fullName: 'Joseph Thompson',
    email: 'joseph.thompson@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 16,
    fullName: 'Sofia Hernandez',
    email: 'sofia.hernandez@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: null,
  },
  {
    id: 17,
    fullName: 'David Young',
    email: 'david.young@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 18,
    fullName: 'Chloe Wilson',
    email: 'chloe.wilson@example.com',
    role: 'admin',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 19,
    fullName: 'Andrew Martin',
    email: 'andrew.martin@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 20,
    fullName: 'Grace Taylor',
    email: 'grace.taylor@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: null,
  },
  {
    id: 21,
    fullName: 'James Anderson',
    email: 'james.anderson@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 22,
    fullName: 'Lily Brown',
    email: 'lily.brown@example.com',
    role: 'admin',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'active',
    avatar: null,
  },
  {
    id: 23,
    fullName: 'Benjamin Harris',
    email: 'benjamin.harris@example.com',
    role: 'user',
    currentPlan: 'basic',
    billing: 'Monthly',
    status: 'active',
    avatar: null,
  },
  {
    id: 24,
    fullName: 'Avery Turner',
    email: 'avery.turner@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: 'https://via.placeholder.com/150',
  },
  {
    id: 24,
    fullName: 'Avery Turner',
    email: 'avery.turner@example.com',
    role: 'user',
    currentPlan: 'premium',
    billing: 'Yearly',
    status: 'inactive',
    avatar: 'https://via.placeholder.com/150',
  },
]
